"set textwidth=79
set autoindent
set smartindent
set number          "numbers on left part of screen
set tabstop=4       "Number of spaces that actual tabs are represented as
set shiftwidth=4    "Number of spaces used for autoindent steps
set cindent
" handle lambda correctly
set cino=j1,(0,ws,Ws,g0
set expandtab       "turns tabs into spaces
set ruler           "tells column and line info on bottom
set showmatch       "highlight match from searching functions
set showmode        "show if in insert or command mode
set nocompatible    "Don't want this in vi mode
set wrapscan      "Don't wrap around the end of the file during search
set showcmd         "show command in bottom bar
set cursorline      "highlight current line
set incsearch       "search as characters are entered
set hlsearch        "highlight matches
set showmatch       "highlight matching [{()}]
set laststatus=2
set smartcase

"toggle search highlight
nnoremap <F2> :set hlsearch!<CR>
"search and replace
nnoremap <F4> :%s/\<<C-r><C-w>\>/
"quicksave
nnoremap <F5> :w<CR>
"toggle line-numbers
nnoremap <F12> :set number!<CR>

filetype indent on  "load filetype-specific indent files
filetype plugin on
syntax on

"c++ main macro
let @m = "i#include <iostream>\n#include <vector>\n#include <string>\n#include <cstdint>\n#include <cstdio>\n#include <numeric>\n#include <algorithm>\n#include <iterator>\n#include <set>\n#include <map>\n#include <utility>\n#include <queue>\n#define ll long long\n\nint main(){\n}\n"
call setreg('L',"/**\n * @file <filename>\n *\n * Copyright 2021 \n * Carnegie Robotics, LLC\n * 4501 Hatfield Street, Pittsburgh, PA 15201\n * https://www.carnegierobotics.com\n *\n * Significant history (date, user, job code, action):\n *  <YYYY-MM-DD>, <user>@carnegierobotics.com, <Project Code>, <Action>.\n */")

colorscheme torte
hi Normal guibg=NONE ctermbg=NONE
